{% set name = "related" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22a99ba805ba3ee6cdf46057accb3925ee2ed579202e5f5c6a648636b96b1490

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - pytest-runner
  run:
    - python >=3.6
    - attrs
    - pyyaml
    - future
    - singledispatch
    - python-dateutil

test:
  imports:
    - related

about:
  home: https://github.com/genomoncology/related
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Related: Straightforward nested object models in Python'
  description: Related is a Python library for creating nested object models that can be serialized to and de-serialized from nested python dictionaries. When paired with other libraries (e.g. PyYAML), Related object models can be used to convert to and from nested data formats (e.g. JSON, YAML).
  doc_url: https://github.com/genomoncology/related
  dev_url: https://github.com/genomoncology/related

extra:
  recipe-maintainers:
    - visze
